name: work_station
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  dio: ^2.1.0
  flutter_swiper: ^1.1.4
  flutter_screenutil: ^0.5.1
  table_calendar: ^1.1.4
  shared_preferences: ^0.5.1+2
  flutter_easyrefresh: ^1.2.7
  fluttertoast: ^3.0.3
  flutter_range_slider: ^1.1.0
  synchronized: 2.1.0
  modal_progress_hud: ^0.1.3
  connectivity: ^0.4.3+1
  marquee_flutter: ^0.1.3
  mqtt_client: ^5.4.0
  flutter_tab_bar_no_ripple: ^0.1.1
  provide: ^1.0.2
  flutter_spinkit: ^3.1.0
  fluro: ^1.4.0
  flutter_marquee:
    git: https://github.com/LiuC520/flutter_marquee.git
  flutter_seekbar:
    git: https://github.com/LiuC520/flutter_seekbar.git

  flutter_datetime_picker:
    git: https://github.com/Realank/flutter_datetime_picker.git


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  - images/bg.png
  - images/icon.png
  - images/home_icon.png
  - images/home_lock.png
  - images/forget_pass_code.png
  - images/forget_pass_phone.png
  - images/forget_pass_lock.png
  - images/home_page_top.png
  - images/home_order_select.png
  - images/home_arrow.png
  - images/home_order_mark.png
  - images/home_order_me.png
  - images/home_order_unselected.png
  - images/home_me_selected.png
  - images/index_me_phone.png
  - images/index_me_lock.png
  - images/order_mark_allow.png
  - images/order_advance_temperature.png
  - images/order_advance_humidity.png
  - images/order_advance_pm.png
  - images/order_advance_ocupy.png
  - images/order_advance_empty.png
  - images/order_advance_employ.png
  - images/order_advance_engross.png
  - images/order_advance_spoil.png
  - images/order_detail_bg.png
  - images/test.png
  - images/order_success_bg.png
  - images/icon_desk_left_1001.png
  - images/icon_desk_right_1001.png
  - images/icon_desk_bottom_1001.png
  - images/icon_desk_top_1001.png
  - images/desk_d_bottom_1001.png
  - images/desk_c_rignt_1101.png
  - images/desk_c_left_1101.png
  - images/desk_a_01_1101.png
  - images/desk_a_02_1101.png
  - images/desk_a_03_1101.png
  - images/desk_a_04_1101.png
  - images/desk_a_05_1101.png
  - images/desk_a_06_1101.png
  - images/desk_d_01_1101.png
  - images/desk_round_small.png
  - images/desk_round_big.png
  - images/desk_e_01_1102.png
  - images/desk_e_01_1103.png
  - images/desk_e_01_1104.png
  - images/desk_e_02_1102.png
  - images/desk_e_02_1103.png
  - images/desk_e_02_1104.png
  - images/desk_e_03_1102.png
  - images/desk_e_03_1103.png
  - images/desk_e_03_1104.png
  - images/desk_d_01_1002.png
  - images/desk_d_01_1003.png
  - images/desk_d_01_1104.png
  - images/desk_d_02_1002.png
  - images/desk_d_02_1003.png
  - images/desk_d_02_1004.png
  - images/desk_c_01_1002.png
  - images/desk_c_01_1003.png
  - images/desk_c_01_1004.png
  - images/desk_c_03_1002.png
  - images/desk_c_03_1003.png
  - images/desk_c_03_1004.png
  - images/desk_a_01_1002.png
  - images/desk_a_01_1003.png
  - images/desk_a_01_1004.png
  - images/desk_a_02_1002.png
  - images/desk_a_02_1003.png
  - images/desk_a_02_1004.png
  - images/desk_a_03_1002.png
  - images/desk_a_03_1003.png
  - images/desk_a_03_1004.png
  - images/desk_a_04_1002.png
  - images/desk_a_04_1003.png
  - images/desk_a_04_1004.png
  - images/desk_a_05_1002.png
  - images/desk_a_05_1003.png
  - images/desk_a_05_1004.png
  - images/desk_a_06_1002.png
  - images/desk_a_06_1003.png
  - images/desk_a_06_1004.png
  - images/desk_f_01_1002.png
  - images/desk_f_01_1003.png
  - images/desk_f_01_1004.png
  - images/order_mark_cancel.png
  - images/order_mark_complete.png
  - images/order_mark_unuse.png
  - images/home_order_icon.png
  - images/order_advance_bg.png
  - images/pt11_1001.png
  - images/pt11_1002.png
  - images/pt11_1003.png
  - images/pt11_1004.png
  - images/pt09_1001.png
  - images/pt09_1002.png
  - images/pt09_1003.png
  - images/pt09_1004.png
  - images/pt02_1001.png
  - images/pt02_1002.png
  - images/pt02_1003.png
  - images/pt02_1004.png
  - images/pt04_1001.png
  - images/pt04_1002.png
  - images/pt04_1003.png
  - images/pt04_1004.png
  - images/pt13_1001.png
  - images/pt13_1002.png
  - images/pt13_1003.png
  - images/pt13_1004.png

  - images/pt14_1001.png
  - images/pt14_1002.png
  - images/pt14_1003.png
  - images/pt14_1004.png

  - images/pt15_1001.png
  - images/pt15_1002.png
  - images/pt15_1003.png
  - images/pt15_1004.png

  - images/pt16_1101.png
  - images/pt16_1102.png
  - images/pt16_1103.png
  - images/pt16_1104.png

  - images/pt18_1001.png
  - images/pt18_1002.png
  - images/pt18_1003.png
  - images/pt18_1004.png

  - images/pt19_1001.png
  - images/pt19_1002.png
  - images/pt19_1003.png
  - images/pt19_1004.png

  - images/pt21_1001.png
  - images/pt21_1002.png
  - images/pt21_1003.png
  - images/pt21_1004.png

  - images/first_desk.png
  - images/second_desk.png
  - images/small_desk.png
  - images/big_desk.png

  - images/air_control_progress15.png
  - images/air_control_progress16.png
  - images/air_control_progress17.png
  - images/air_control_progress18.png
  - images/air_control_progress19.png
  - images/air_control_progress20.png
  - images/air_control_progress21.png
  - images/air_control_progress22.png
  - images/air_control_progress23.png
  - images/air_control_progress24.png
  - images/air_control_progress25.png
  - images/air_control_progress26.png
  - images/air_control_progress27.png
  - images/air_control_progress28.png
  - images/air_control_progress29.png
  - images/air_control_progress30.png

  - images/air_cool.png
  - images/air_cool_icon.png
  - images/air_close.png
  - images/air_hot.png
  - images/air_humidity.png
  - images/air_btn.png
  - images/air_wind.png
  - images/air_control_topbg_humidity.png

  - images/index_orical_click.png
  - images/index_orical.png
  - images/order_air.png

  - images/small_desk_all.png
  - images/big_desk_all.png


  - images/air_control_humidity_wind.png
  - images/back.png

  - images/air_control_topbg_hot.png
  - images/air_control_progress_zero.png
  - images/air_control_progress_full.png
  - images/air_control_reduce_progress.png
  - images/air_control_add_progress.png

  - images/air_control_click_cool.png
  - images/air_control_click_hot.png
  - images/air_control_click_humidity.png
  - images/air_control_click_wind.png


  - images/air_control_topbg_cool.png
  - images/air_control_topbg_humidity.png
  - images/air_control_topbg_wind.png
  - images/air_control_close.png



  - images/air_control_close_click_hot.png
  - images/air_control_close_click_cool.png
  - images/air_control_close_click_wind.png
  - images/air_control_close_click_humidity.png


  - images/air_control_cool_click_cool.png
  - images/air_control_cool_click_hot.png
  - images/air_control_cool_click_wind.png
  - images/air_control_cool_click_humidity.png


  - images/air_control_hot_click_cool.png
  - images/air_control_hot_click_hot.png
  - images/air_control_hot_click_humidity.png
  - images/air_control_hot_click_wind.png

  - images/air_control_humidity_click_cool.png
  - images/air_control_humidity_click_cool.png
  - images/air_control_humidity_click_wind.png
  - images/air_control_humidity_click_humidity.png


  - images/air_control_wind_click_cool.png
  - images/air_control_wind_click_hot.png
  - images/air_control_wind_click_wind.png
  - images/air_control_wind_click_humidity.png


  - images/splash_page1.png
  - images/splash_logo.png
  - images/net_work_error.png
  - images/abort_me.png
  - images/order_mark_icon.png

  - images/first_rectangle_desk.png
  - images/second_rectangle_desk.png
  - images/third_rectangle_desk.png


  - images/index_lighting_icon.png

  - images/lighting_list_four_icon.png
  - images/lighting_list_three_icon.png
  - images/lighting_list_two_icon.png

  - images/lighting_list_wifi_level1.png
  - images/lighting_list_wifi_level2.png
  - images/lighting_list_wifi_level3.png
  - images/lighting_list_wifi_level4.png

  - images/lighting_list_back.png
  - images/lighting_detail_setting.png

  - images/lighting_detail_off.png
  - images/lighting_detail_on.png

  - images/lighting_control_on.png
  - images/lighting_control_off.png

  - images/lighting_switch_on.png
  - images/lighting_switch_off.png

  - images/lighting_radio_on.png
  - images/lighting_radio_off.png

  - images/clock_all_alarm.png
  - images/arrow_down.png
  - images/arrow_up.png
  - images/lighting_delete.png





  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.io/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.io/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.io/custom-fonts/#from-packages
